apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: c1-tomcat
  labels:
    app: c1-tomcat
spec:
  type: NodePort
  ports:
  - port: 8080
    name: c1-tomcat
    targetPort: 8080
    nodePort: 30100
  selector:
    app: c1-tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-tomcat
  name: c1-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-tomcat
    spec:
      containers:
      - name: c1-tomcat
        image: $K8S_REGISTRY/c1-tomcat:latest
        imagePullPolicy: Always
        env:
        - name: TREND_AP_KEY
          value: $APPSEC_KEY
        - name: TREND_AP_SECRET
          value: $APPSEC_SECRET
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
